package finestres;

import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/*
 * @author aNDREUET
 */
public class Administrador extends javax.swing.JFrame {

    String user, nombre_usuario, apellido_usuario;
    
    /*
     * Constructor del form Administrador
     */
    public Administrador() {
        initComponents();
        user = Interface.usuario;
     
        setSize(650, 450);
        setResizable(false);
        setTitle("Rol: Administrador - Sesión de " + user);
        setLocationRelativeTo(null);

        //mata procesos en segundo plano
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        // Fondo de pantalla de mi aplicación
        ImageIcon wallpaper = new ImageIcon("src/imatges/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection con = Conexion.conector();
            //  recupero nombre y apellidos del user que ha entrado
            String sql = "select nombre, apellidos from Usuarios where user = '" + user + "'";
            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre");
                apellido_usuario = rs.getString("apellidos");
                jLabel_NombreUsuario.setText(" " + nombre_usuario + " " + apellido_usuario);
            }
        } catch (SQLException e) {
            System.err.println("Error en la consulta del nombre del Administrador " + e);
        }
    }

    //
    //  Colocamos en icono que aparecerá en la barra de tareas
    //  Que nos nos salga la famosa tacita de café
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imatges/logohpp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jButton_GestionarUsuarios = new javax.swing.JButton();
        jButton_GestionarIncidenciasAdmin = new javax.swing.JButton();
        jButton_Tecnico = new javax.swing.JButton();
        jButton_Cliente = new javax.swing.JButton();
        jButton_GestionarEquipos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NombreUsuario.setForeground(java.awt.Color.white);
        jLabel_NombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/badge-admin.png"))); // NOI18N
        jLabel_NombreUsuario.setText("jLabel1");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_GestionarUsuarios.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/informationuser.png"))); // NOI18N
        jButton_GestionarUsuarios.setToolTipText("Altas, consultas, listados y registro de equipos de usuario");
        jButton_GestionarUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 80, 80));

        jButton_GestionarIncidenciasAdmin.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarIncidenciasAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/incidencias.png"))); // NOI18N
        jButton_GestionarIncidenciasAdmin.setToolTipText("Asignar incidencias, establecer prioridades y niveles, listados");
        jButton_GestionarIncidenciasAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarIncidenciasAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarIncidenciasAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarIncidenciasAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 80, 80));

        jButton_Tecnico.setBackground(new java.awt.Color(10, 47, 63));
        jButton_Tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/menu_tecnico.png"))); // NOI18N
        jButton_Tecnico.setToolTipText("Acceso al Menú del Técnico");
        jButton_Tecnico.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 80));

        jButton_Cliente.setBackground(new java.awt.Color(10, 47, 63));
        jButton_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/menu_cliente.png"))); // NOI18N
        jButton_Cliente.setToolTipText("Acceso al Menú del Cliente");
        jButton_Cliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 80, 80));

        jButton_GestionarEquipos.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/equipos.png"))); // NOI18N
        jButton_GestionarEquipos.setToolTipText("Consultas, modificaciones y listados ");
        jButton_GestionarEquipos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, 80));

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Gestionar Usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Gestionar Incidencias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Menú Rol Técnico");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Menú Rol Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Gestionar Equipos Usuarios");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Andreu Garcia Coll - UIB 2020");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel_Wallpaper.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/wallpaperPrincipal.jpg"))); // NOI18N
        jLabel_Wallpaper.setToolTipText("");
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarUsuariosActionPerformed

        // Creo una instacia de clases
        GestionarUsuarios gestionarUsuarios = new GestionarUsuarios();
        gestionarUsuarios.setVisible(true);

    }//GEN-LAST:event_jButton_GestionarUsuariosActionPerformed

    private void jButton_GestionarIncidenciasAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarIncidenciasAdminActionPerformed
        
        // Creo una instancia de clases
        GestionarIncidenciasAdmin gestionarIncidenciasAdmin = new GestionarIncidenciasAdmin();
        gestionarIncidenciasAdmin.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarIncidenciasAdminActionPerformed

    private void jButton_TecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TecnicoActionPerformed
        // creo una instalación de clases
        Tecnico tecnico = new Tecnico();
        tecnico.setVisible(true);
    }//GEN-LAST:event_jButton_TecnicoActionPerformed

    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
        // Creo una instacia de clases
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jButton_GestionarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarEquiposActionPerformed
        
        // creo una instancia de clases
        GestionarEquipos gestionarEquipos = new GestionarEquipos();
        gestionarEquipos.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_GestionarEquipos;
    private javax.swing.JButton jButton_GestionarIncidenciasAdmin;
    private javax.swing.JButton jButton_GestionarUsuarios;
    private javax.swing.JButton jButton_Tecnico;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
