package finestres;

import clases.Conexion;
import java.sql.*;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/*
 * @author aNDREUET
 */
public class Cliente extends javax.swing.JFrame {

    String user, nombre_usuario, apellido_usuario;
    //
    // sesion_usuario actuará como Flag 
    // la ventana de Cliente no dejará de ejecutarse si 
    // he arrancado esta ventana desde la sesión de Administrador
    //
    int usuario_sesion;

    /**
     * Constructor del form Cliente
     */
    public Cliente() {
        initComponents();
        user = Interface.usuario;
        usuario_sesion = Interface.usuario_sesion;

        setSize(650, 450);
        setResizable(false);
        setTitle("Rol: Cliente - Sesión de " + user);
        setLocationRelativeTo(null);
        //
        // dentro del constructor creo una estructura condicional para que no se
        // cierre este Interface si he iniciado sesión de Administrador o si se
        // ha iniciado como Técnico y no finalice a menos que se cierren las 
        // Interface de Administrador.java (Rol Administrador)
        // Interface de Tecnico.java (Rol Tecnico)
        // En cambio, si estoy he iniciado sesión como Cliente el Interface
        // Cliente.java se cerrará y por tanto finalizará el programa
        //
        if (usuario_sesion == 1 || usuario_sesion == 2) {
            // he iniciado sesión como Administrador o Técnico
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            // he iniciado sesión como Cliente
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        // Fondo de pantalla de mi aplicación
        ImageIcon wallpaper = new ImageIcon("src/imatges/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection con = Conexion.conector();
            //  recupero nombre y apellidos del user que ha entrado
            String sql = "select nombre, apellidos from Usuarios where user = '" + user + "'";
            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre");
                apellido_usuario = rs.getString("apellidos");
                // visualizo en el Interface de Cliente nombre y apellidos user
                jLabel_NombreUsuario.setText(" " + nombre_usuario + " " + apellido_usuario);
            }
        } catch (SQLException e) {
            System.err.println("Error en la consulta del nombre del Cliente " + e);
        }
    }

    //
    //  Coloco el icono que aparecerá en la barra de tareas
    //
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imatges/logohpp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_FalloHardware = new javax.swing.JButton();
        jButton_FalloSoftware = new javax.swing.JButton();
        jButton_InformaProblema = new javax.swing.JButton();
        jButton_GestionarIncidenciasCliente = new javax.swing.JButton();
        jButton_GestionarEquipos = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NombreUsuario.setForeground(java.awt.Color.white);
        jLabel_NombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/badge-user.png"))); // NOI18N
        jLabel_NombreUsuario.setText("jLabel1");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Histórico Incidentes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Mis equipos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Fallo Hardware");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Fallo Software");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Otros Fallos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Andreu Garcia Coll - UIB 2020");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jButton_FalloHardware.setBackground(new java.awt.Color(10, 47, 63));
        jButton_FalloHardware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/Fallo-Hardware.PNG"))); // NOI18N
        jButton_FalloHardware.setToolTipText("Incidente tipo Hardware");
        jButton_FalloHardware.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_FalloHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FalloHardwareActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_FalloHardware, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 80));

        jButton_FalloSoftware.setBackground(new java.awt.Color(10, 47, 63));
        jButton_FalloSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/Problema-Software.PNG"))); // NOI18N
        jButton_FalloSoftware.setToolTipText("Incidente tipo Software");
        jButton_FalloSoftware.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_FalloSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FalloSoftwareActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_FalloSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 80, 80));

        jButton_InformaProblema.setBackground(new java.awt.Color(10, 47, 63));
        jButton_InformaProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/Informar-Problema.PNG"))); // NOI18N
        jButton_InformaProblema.setToolTipText("Cualquier otro tipo de incidente");
        jButton_InformaProblema.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_InformaProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InformaProblemaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_InformaProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 80, 80));

        jButton_GestionarIncidenciasCliente.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarIncidenciasCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/Reportar-Incidencias.PNG"))); // NOI18N
        jButton_GestionarIncidenciasCliente.setToolTipText("Mis incidentes");
        jButton_GestionarIncidenciasCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarIncidenciasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarIncidenciasClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarIncidenciasCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 80, 80));

        jButton_GestionarEquipos.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/equipos.png"))); // NOI18N
        jButton_GestionarEquipos.setToolTipText("Equipos que tengo registrados");
        jButton_GestionarEquipos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 80));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GestionarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarEquiposActionPerformed
        
        // creo una instancia de clases
        GestionarEquiposClientes gestionarEquiposClientes = new GestionarEquiposClientes();
        gestionarEquiposClientes.setVisible(true);
     
    }//GEN-LAST:event_jButton_GestionarEquiposActionPerformed

    private void jButton_InformaProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InformaProblemaActionPerformed

        // creo una instancia de clases
        FalloOtro falloOtro = new FalloOtro();
        falloOtro.setVisible(true);

    }//GEN-LAST:event_jButton_InformaProblemaActionPerformed

    private void jButton_FalloHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FalloHardwareActionPerformed

        // creo una instancia de clases
        FalloHardware falloHardware = new FalloHardware();
        falloHardware.setVisible(true);

    }//GEN-LAST:event_jButton_FalloHardwareActionPerformed

    private void jButton_FalloSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FalloSoftwareActionPerformed

        // creo una instancia de clases
        FalloSoftware falloSoftware = new FalloSoftware();
        falloSoftware.setVisible(true);

    }//GEN-LAST:event_jButton_FalloSoftwareActionPerformed

    private void jButton_GestionarIncidenciasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarIncidenciasClienteActionPerformed

        // creo una instancia de clases
        GestionarIncidenciasCliente gestionarIncidenciasCliente = new GestionarIncidenciasCliente();
        gestionarIncidenciasCliente.setVisible(true);

    }//GEN-LAST:event_jButton_GestionarIncidenciasClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_FalloHardware;
    private javax.swing.JButton jButton_FalloSoftware;
    private javax.swing.JButton jButton_GestionarEquipos;
    private javax.swing.JButton jButton_GestionarIncidenciasCliente;
    private javax.swing.JButton jButton_InformaProblema;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
