package finestres;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Properties;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * @author aNDREUET
 */
public class InformacionEquipo extends javax.swing.JFrame {

    int IDcliente_update = 0, IDequipo = 0;
    String user = "", nom_cliente = "";
    int IDuser = 0;
    int estatus = 0;

    /**
     * Constructor del form InformacionEquipo
     */
    public InformacionEquipo() {
        initComponents();
        user = Interface.usuario;
        IDuser = Interface.IDuser;
        IDequipo = GestionarEquipos.IDequipo_update;
        IDcliente_update = GestionarClientes.IDcliente_update;

        // recuperamos datos del equipo de la tabla Equipos
        try {

            Connection con = Conexion.conector();
            String sql = "SELECT  * FROM Usuarios, Equipos E WHERE ";
            sql += "idUsuario = Usuarios_idUsuario AND ";
            sql += "idEquipos = " + IDequipo;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                cmb_tipoequipo.setSelectedItem(rs.getString("tipo"));
                cmb_marcas.setSelectedItem(rs.getString("marca"));
                estatus = rs.getInt("E.habilitado");
                nom_cliente = rs.getString("nombre") + " " + rs.getString("apellidos");
                switch (estatus) {
                    case 0:
                        cmb_estatus.setSelectedItem("Inactivo");
                        break;
                    case 1:
                        cmb_estatus.setSelectedItem("Activo");
                        break;
                    case 2:
                        jLabel_Titulo.setText("Información del Equipo - Sólo consulta");
                        cmb_estatus.setSelectedItem("Abierta incidencia");
                        cmb_estatus.enable(false);
                        cmb_marcas.enable(false);
                        cmb_tipoequipo.enable(false);
                        txt_NombreCliente.setEditable(false);
                        txt_modelo.setEditable(false);
                        txt_num_serie.setEditable(false);
                        txt_ultima_Modificacion.setEditable(false);
                        txt_fecha.setEditable(false);
                        jTextPane_observaciones.setEditable(false);

                        break;
                    default:
                        break;
                }
                txt_NombreCliente.setText(nom_cliente);
                txt_modelo.setText(rs.getString("modelo"));
                txt_num_serie.setText(rs.getString("num_serie"));
                txt_ultima_Modificacion.setText(Integer.toString(rs.getInt("usuarios_idUsuario")));
                txt_fecha.setText(rs.getTimestamp("fecha_compra").toString());
                // observaciones del form
                jTextPane_observaciones.setText(rs.getString("observaciones"));
               
                con.close();

            }
        } catch (SQLException e) {
            System.err.println("Error al consultar datos del Equipo " + e);
            JOptionPane.showMessageDialog(null, "Error al consultar datos del equipo, contacte con el Administrador");
        }

        // ahora si que puedo ponerlo porque ya tengo el valor de nombre_cliente
        setTitle("Equipo perteneciente a: " + nom_cliente);
        setSize(800, 550);
        setResizable(false);  // no se modificar el tamaño del interfaz
        setLocationRelativeTo(null); // centrar la interfaz al ejecutar

        // evita que se cierre el programa cuando cerramos esta interfaz
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        // Fondo de pantalla de mi aplicación
        ImageIcon wallpaper = new ImageIcon("src/imatges/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

    }

    //
    //  Colocamos en icono que aparecerá en la barra de tareas
    //  Que nos nos aparezca la famosa tacita de Café
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imatges/logohpp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Nombre1 = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jLabel_Nombre3 = new javax.swing.JLabel();
        jLabel_Nombre4 = new javax.swing.JLabel();
        jLabel_Nombre5 = new javax.swing.JLabel();
        jLabel_Nombre6 = new javax.swing.JLabel();
        jLabel_Nombre7 = new javax.swing.JLabel();
        jLabel_Nombre8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        txt_NombreCliente = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_num_serie = new javax.swing.JTextField();
        txt_ultima_Modificacion = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        cmb_marcas = new javax.swing.JComboBox<>();
        cmb_estatus = new javax.swing.JComboBox<>();
        jButton_Actualizar = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(java.awt.Color.white);
        jLabel_Titulo.setText("Información de equipo");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre.setForeground(java.awt.Color.white);
        jLabel_Nombre.setText("Nombre del  cliente:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel_Nombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre1.setForeground(java.awt.Color.white);
        jLabel_Nombre1.setText("Tipo de equipo:");
        getContentPane().add(jLabel_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel_Nombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre2.setForeground(java.awt.Color.white);
        jLabel_Nombre2.setText("Marca:");
        getContentPane().add(jLabel_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel_Nombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre3.setForeground(java.awt.Color.white);
        jLabel_Nombre3.setText("Modelo:");
        getContentPane().add(jLabel_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel_Nombre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre4.setForeground(java.awt.Color.white);
        jLabel_Nombre4.setText("Número de serie:");
        getContentPane().add(jLabel_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel_Nombre5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre5.setForeground(java.awt.Color.white);
        jLabel_Nombre5.setText("Fecha:");
        getContentPane().add(jLabel_Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel_Nombre6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre6.setForeground(java.awt.Color.white);
        jLabel_Nombre6.setText("Última modificación:");
        getContentPane().add(jLabel_Nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel_Nombre7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre7.setForeground(java.awt.Color.white);
        jLabel_Nombre7.setText("Status:");
        getContentPane().add(jLabel_Nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        jLabel_Nombre8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Nombre8.setForeground(java.awt.Color.white);
        jLabel_Nombre8.setText("Observaciones:");
        getContentPane().add(jLabel_Nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jTextPane_observaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 360, 140));

        txt_NombreCliente.setEditable(false);
        txt_NombreCliente.setBackground(new java.awt.Color(141, 159, 166));
        txt_NombreCliente.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_NombreCliente.setForeground(java.awt.Color.white);
        txt_NombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_NombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, 25));

        txt_modelo.setBackground(new java.awt.Color(141, 159, 166));
        txt_modelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_modelo.setForeground(java.awt.Color.white);
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_modelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 260, 25));

        txt_num_serie.setBackground(new java.awt.Color(141, 159, 166));
        txt_num_serie.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_num_serie.setForeground(java.awt.Color.white);
        txt_num_serie.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_num_serie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_num_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 25));

        txt_ultima_Modificacion.setBackground(new java.awt.Color(141, 159, 166));
        txt_ultima_Modificacion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_ultima_Modificacion.setForeground(java.awt.Color.white);
        txt_ultima_Modificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultima_Modificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_ultima_Modificacion.setEnabled(false);
        getContentPane().add(txt_ultima_Modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 25));

        txt_fecha.setEditable(false);
        txt_fecha.setBackground(new java.awt.Color(141, 159, 166));
        txt_fecha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_fecha.setForeground(java.awt.Color.white);
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 210, 25));

        cmb_tipoequipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifunción", "Plotter" }));
        getContentPane().add(cmb_tipoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        cmb_marcas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "MSI", "Samsung", "Toshiba", "Xerox" }));
        cmb_marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_marcasActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        cmb_estatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Abierta incidencia" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jButton_Actualizar.setBackground(new java.awt.Color(16, 72, 75));
        jButton_Actualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Actualizar.setForeground(java.awt.Color.white);
        jButton_Actualizar.setText("Actualizar equipo");
        jButton_Actualizar.setBorder(null);
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 210, 35));

        jLabel_footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_footer.setText("Andreu Garcia Coll - UIB 2020");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

        int validacion = 0, estatus_cmb = 0;
        // variables de alojamiento temporal de la información a modificar
        String tipo_equipo, marca, modelo, num_serie, observaciones;
        
        if (estatus == 2) { //  si el equipo tiene una incidencia abierta no lo podemos actualizar
            
            jButton_Actualizar.enable(false);
            JOptionPane.showMessageDialog(null, "Abierta incidencia de este equipo. Disponible únicamente consulta de la información hasta resolución");
            
        } else {

            // guardo la información de los combo Box
            tipo_equipo = cmb_tipoequipo.getSelectedItem().toString();
            marca = cmb_marcas.getSelectedItem().toString();
            estatus_cmb = cmb_estatus.getSelectedIndex();
            // y ahora la de los campos de texto
            modelo = txt_modelo.getText().trim();
            num_serie = txt_num_serie.getText().trim();
            observaciones = jTextPane_observaciones.getText();
            //verifico que los campos no están vacíos
            if (modelo.equals("")) {
                validacion++;
                txt_modelo.setBackground(new Color(255,180,40));
            }
            if (num_serie.equals("")) {
                validacion++;
                txt_num_serie.setBackground(new Color(255,180,40));
            }
            if (observaciones.equals("")) {
                jTextPane_observaciones.setText("Sin observaciones");
                observaciones = jTextPane_observaciones.getText();
            }

            if (validacion == 0) {

                try {
                    // acceso a la base de datos para modificar la información
                    Connection con = Conexion.conector();
                    String sql = "UPDATE Equipos SET tipo=?, marca=?, modelo=?, num_serie=?, ";
                    sql += "observaciones=?, habilitado=? ";
                    sql += "WHERE idEquipos = '" + IDequipo + "'";
                    PreparedStatement pst = con.prepareStatement(sql);

                    // envío los valores de las variables temporales a la bd
                    pst.setString(1, tipo_equipo);
                    pst.setString(2, marca);
                    pst.setString(3, modelo);
                    pst.setString(4, num_serie);
                    pst.setString(5, observaciones);
                    // que pasa con su estado
                    switch (estatus_cmb) {
                        case 0: // el equipo está activo
                            pst.setInt(6, 1);
                            break;
                        case 1: // el equipo está inactivo
                            pst.setInt(6, 0);
                            break;
                        case 2: // el equipo tiene una incidencia abierta
                            pst.setInt(6, 2);
                            break;
                        default:
                            break;
                    }

                    pst.executeUpdate();

                    con.close();

                    txt_NombreCliente.setBackground(new Color(40,190,255));
                    txt_fecha.setBackground(new Color(40,190,255));
                    txt_modelo.setBackground(new Color(40,190,255));
                    txt_num_serie.setBackground(new Color(40,190,255));
                    txt_ultima_Modificacion.setText(user);

                    JOptionPane.showMessageDialog(null, "Equipo actualizado correctamente");
                    Limpiar();
                    this.dispose();

                } catch (SQLException e) {
                    System.err.println("Error al actualizar datos del Equipo " + e);
                    JOptionPane.showMessageDialog(null, "Error al actualizar datos del equipo, contacte con el Administrador");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
            }

        }
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void cmb_marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_marcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_marcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_marcas;
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre1;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Nombre3;
    private javax.swing.JLabel jLabel_Nombre4;
    private javax.swing.JLabel jLabel_Nombre5;
    private javax.swing.JLabel jLabel_Nombre6;
    private javax.swing.JLabel jLabel_Nombre7;
    private javax.swing.JLabel jLabel_Nombre8;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_num_serie;
    private javax.swing.JTextField txt_ultima_Modificacion;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        txt_NombreCliente.setText("");
        txt_fecha.setText("");
        txt_modelo.setText("");
        txt_num_serie.setText("");
        jTextPane_observaciones.setText("");
    }
}
