package finestres;

import clases.Conexion;
import java.sql.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;



/*
 * @author aNDREUET
 */
public class Tecnico extends javax.swing.JFrame {

    String user, nombre_usuario, apellido_usuario;
    //
    // usuario_sesion actuará como Flag 
    // la ventana de Tecnico no dejará de ejecutarse si 
    // he arrancado esta ventana desde la sesión de Administrador
    //
    int usuario_sesion; // 

    /**
     * Constructor del form Tecnico
     */
    public Tecnico() {
        initComponents();
        user = Interface.usuario;
        usuario_sesion = Interface.usuario_sesion;
        setSize(650, 450);
        setResizable(false);
        setTitle("Rol: Técnico - Sesión de " + user);
        setLocationRelativeTo(null);
        //
        // dentro del constructor creo una estructura condicional para que no se
        // cierre este Interface si he iniciado sesión de Administrador y no
        // finalice a menos que se cierre la Interface de Administrador.java
        // 
        // En cambio, si estoy he iniciado sesión como Técnico el Interface
        // Tecnico.java se cerrará y por tanto finalizará el programa
        //
        if (usuario_sesion == 1) {
            // he iniciado sesión como Administrador
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            // he iniciado sesión como Técnico
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        // Fondo de pantalla de mi aplicación
        ImageIcon wallpaper = new ImageIcon("src/imatges/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection con = Conexion.conector();
            //  recupero nombre y apellidos del user que ha entrado
            String sql = "select nombre, apellidos from Usuarios where user = '" + user + "'";
            PreparedStatement pst = con.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombre_usuario = rs.getString("nombre");
                apellido_usuario = rs.getString("apellidos");
                // visualizo en el Interface de Técnico nombre y apellidos user
                jLabel_NombreUsuario.setText("Bienvenido " + nombre_usuario + " " + apellido_usuario);
            }
        } catch (SQLException e) {
            System.err.println("Error en la consulta del nombre del Técnico " + e);
        }
    }

    //
    //  Colocamos en icono que aparecerá en la barra de tareas
    //
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imatges/logohpp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_GestionarClientes = new javax.swing.JButton();
        jButton_GestionarIncidencias = new javax.swing.JButton();
        jButton_Cliente = new javax.swing.JButton();
        jButton_GestionarEquipos = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(550, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_NombreUsuario.setForeground(java.awt.Color.white);
        jLabel_NombreUsuario.setText("jLabel1");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Gestionar Clientes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Andreu Garcia Coll - UIB 2020");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Menú Rol Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Gestión Equipos Cliente");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Gestionar Incidencias");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jButton_GestionarClientes.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/informationuser.png"))); // NOI18N
        jButton_GestionarClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 80));

        jButton_GestionarIncidencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/apoyo-tecnico.png"))); // NOI18N
        jButton_GestionarIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarIncidenciasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 80, 80));

        jButton_Cliente.setBackground(new java.awt.Color(10, 47, 63));
        jButton_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/tecnico.png"))); // NOI18N
        jButton_Cliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 80, 80));

        jButton_GestionarEquipos.setBackground(new java.awt.Color(10, 47, 63));
        jButton_GestionarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imatges/equipos.png"))); // NOI18N
        jButton_GestionarEquipos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_GestionarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 80, 80));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarClientesActionPerformed
        //  creamos una instancia de clases

        // clase nombre_objeto = nuevo objeto de la misma clase;
        GestionarClientes gestionarClientes = new GestionarClientes();
        gestionarClientes.setVisible(true); // objeto.metodo
    }//GEN-LAST:event_jButton_GestionarClientesActionPerformed

    private void jButton_GestionarIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarIncidenciasActionPerformed

        // creo una instancia de clases
        GestionarIncidenciasTecnico gestionarIncidenciasTecnico = new GestionarIncidenciasTecnico();
        gestionarIncidenciasTecnico.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarIncidenciasActionPerformed

    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
        // Creo una instacia de clases
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jButton_GestionarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarEquiposActionPerformed

        // creo una instancia de clases
        GestionarEquipos gestionarEquipos = new GestionarEquipos();
        gestionarEquipos.setVisible(true);

    }//GEN-LAST:event_jButton_GestionarEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_GestionarClientes;
    private javax.swing.JButton jButton_GestionarEquipos;
    private javax.swing.JButton jButton_GestionarIncidencias;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
